version: "3"
services:
    mysql:
        container_name: some-mysql
        image: mysql:latest
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: prestashop
        networks:
            - prestashop_network
    prestashop:
        container_name: prestashop
        image: prestashop/prestashop:latest # It will get the latest version of PrestaShop. If you need a specific version, you can specify it here.
        restart: unless-stopped
        depends_on:
            - mysql
        ports:
            - 8080:80
        environment:
            DB_SERVER: some-mysql
            DB_NAME: prestashop
            DB_USER: root
            DB_PASSWD: admin
            PS_FOLDER_ADMIN: admin4577
            PS_FOLDER_INSTALL: install4577
        networks:
            - prestashop_network
networks:
    prestashop_network:
